export interface PresetTheme {
  themeName: string;
  primaryColor: string;
  secondaryColor: string;
  backgroundColor: string;
  foregroundColor: string;
  radius: string;
  shadows: string;
  cursor: "heart" | "star" | "sparkle" | "flower" | "none";
  loader: "gift" | "cake" | "heart" | "star";
  fontHeading: string;
  fontBody: string;
  fontHandwriting: string;
  backgroundAnimation: "balloons" | "confetti" | "hearts" | "stars" | "petals" | "none";
  stickers: string[];
  icons: string;
  balloonsEnabled: boolean;
  confettiEnabled: boolean;
  fireworksEnabled: boolean;
  buttonStyle: "rounded" | "pills" | "square" | "glass";
  cardStyle: "flat" | "shadow" | "glass" | "bordered";
  pageTransition: "fade" | "slide" | "scale" | "flip";
}

export interface PresetMascot {
  type: string;
  defaultPose: string;
  animationStyle: "floating" | "bounce" | "wiggle" | "none";
  size: number;
  positionX: number;
  positionY: number;
  enableFloating: boolean;
  enableInteractions: boolean;
  enableBirthdayOutfit: boolean;
}

export interface OccasionPreset {
  name: string;
  bgMusicUrl: string;
  theme: PresetTheme;
  mascot: PresetMascot;
  suggestedCaptions: {
    heading: string;
    subheading: string;
    quote: string;
    buttonText: string;
    footerText: string;
  };
}

export const OCCASION_PRESETS: Record<string, OccasionPreset> = {
  birthday: {
    name: "Classic Birthday",
    bgMusicUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    theme: {
      themeName: "Birthday Fun",
      primaryColor: "#FFD1DC",
      secondaryColor: "#E8DEF8",
      backgroundColor: "#FFF8F8",
      foregroundColor: "#4A3B32",
      radius: "24px",
      shadows: "md",
      cursor: "sparkle",
      loader: "cake",
      fontHeading: "Poppins",
      fontBody: "Nunito",
      fontHandwriting: "Caveat",
      backgroundAnimation: "balloons",
      stickers: ["🎈", "🎂", "🎉", "🎁"],
      icons: "outline",
      balloonsEnabled: true,
      confettiEnabled: true,
      fireworksEnabled: true,
      buttonStyle: "rounded",
      cardStyle: "shadow",
      pageTransition: "fade",
    },
    mascot: {
      type: "giraffe",
      defaultPose: "idle",
      animationStyle: "floating",
      size: 160,
      positionX: 50,
      positionY: 80,
      enableFloating: true,
      enableInteractions: true,
      enableBirthdayOutfit: true,
    },
    suggestedCaptions: {
      heading: "A Very Special Gift For You ❤️",
      subheading: "Happy Birthday! Today is Your Day!",
      quote: "Make a wish! Blow out the candles and let's celebrate another amazing year!",
      buttonText: "Open Scrapbook",
      footerText: "Made with love for you 🎂",
    }
  },
  luxury_birthday: {
    name: "Luxury Birthday",
    bgMusicUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
    theme: {
      themeName: "Gilded Velvet",
      primaryColor: "#D4AF37",
      secondaryColor: "#1A1A1A",
      backgroundColor: "#111111",
      foregroundColor: "#F5F5F5",
      radius: "16px",
      shadows: "lg",
      cursor: "star",
      loader: "star",
      fontHeading: "Playfair Display",
      fontBody: "Inter",
      fontHandwriting: "Great Vibes",
      backgroundAnimation: "stars",
      stickers: ["👑", "💎", "🥂", "✨"],
      icons: "solid",
      balloonsEnabled: false,
      confettiEnabled: true,
      fireworksEnabled: true,
      buttonStyle: "square",
      cardStyle: "glass",
      pageTransition: "scale",
    },
    mascot: {
      type: "lion",
      defaultPose: "celebrate",
      animationStyle: "floating",
      size: 160,
      positionX: 50,
      positionY: 80,
      enableFloating: true,
      enableInteractions: true,
      enableBirthdayOutfit: true,
    },
    suggestedCaptions: {
      heading: "Celebrating Excellence ✨",
      subheading: "Wishing You an Elegant Birthday",
      quote: "Success is not just about milestones, but celebrating the beautiful journey of life.",
      buttonText: "Enter Gala Preview",
      footerText: "Class, Elegance & Love 🥂",
    }
  },
  cute_birthday: {
    name: "Cute Birthday",
    bgMusicUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    theme: {
      themeName: "Fluffy Cotton",
      primaryColor: "#FFC1CC",
      secondaryColor: "#FFF9C4",
      backgroundColor: "#FFF5F7",
      foregroundColor: "#5D4037",
      radius: "28px",
      shadows: "md",
      cursor: "heart",
      loader: "cake",
      fontHeading: "Poppins",
      fontBody: "Nunito",
      fontHandwriting: "Caveat",
      backgroundAnimation: "petals",
      stickers: ["🐰", "🌸", "🧁", "🎀"],
      icons: "outline",
      balloonsEnabled: true,
      confettiEnabled: true,
      fireworksEnabled: false,
      buttonStyle: "pills",
      cardStyle: "shadow",
      pageTransition: "fade",
    },
    mascot: {
      type: "bunny",
      defaultPose: "hold_cake",
      animationStyle: "bounce",
      size: 155,
      positionX: 50,
      positionY: 80,
      enableFloating: false,
      enableInteractions: true,
      enableBirthdayOutfit: true,
    },
    suggestedCaptions: {
      heading: "Sending Warm Fluffy Hugs! 🌸",
      subheading: "A Tiny Birthday Surprise Inside",
      quote: "You are sweeter than a chocolate cupcake with pink sprinkles on top!",
      buttonText: "Unlock Sweets",
      footerText: "Made with sweet sugar & hugs 🐰",
    }
  },
  kids_birthday: {
    name: "Kids Birthday",
    bgMusicUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
    theme: {
      themeName: "Toybox Carnival",
      primaryColor: "#FFEB3B",
      secondaryColor: "#4CAF50",
      backgroundColor: "#E3F2FD",
      foregroundColor: "#0D47A1",
      radius: "32px",
      shadows: "md",
      cursor: "sparkle",
      loader: "gift",
      fontHeading: "Montserrat",
      fontBody: "Nunito",
      fontHandwriting: "Patrick Hand",
      backgroundAnimation: "confetti",
      stickers: ["🦖", "🚀", "🍭", "🎈"],
      icons: "solid",
      balloonsEnabled: true,
      confettiEnabled: true,
      fireworksEnabled: true,
      buttonStyle: "rounded",
      cardStyle: "bordered",
      pageTransition: "flip",
    },
    mascot: {
      type: "dinosaur",
      defaultPose: "jump",
      animationStyle: "bounce",
      size: 150,
      positionX: 50,
      positionY: 80,
      enableFloating: false,
      enableInteractions: true,
      enableBirthdayOutfit: true,
    },
    suggestedCaptions: {
      heading: "Ready for Adventure? 🚀",
      subheading: "Happy Birthday Kiddo!",
      quote: "Get ready to play games, eat cake, and pop balloons because you are awesome!",
      buttonText: "Let's Play!",
      footerText: "Have a blast today! 🍭",
    }
  },
  romantic_birthday: {
    name: "Romantic Birthday",
    bgMusicUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
    theme: {
      themeName: "Midnight Rose",
      primaryColor: "#E91E63",
      secondaryColor: "#F8BBD0",
      backgroundColor: "#FFF0F5",
      foregroundColor: "#3E2723",
      radius: "24px",
      shadows: "lg",
      cursor: "heart",
      loader: "heart",
      fontHeading: "Playfair Display",
      fontBody: "Open Sans",
      fontHandwriting: "Great Vibes",
      backgroundAnimation: "hearts",
      stickers: ["🌹", "💍", "🕯️", "💖"],
      icons: "solid",
      balloonsEnabled: false,
      confettiEnabled: false,
      fireworksEnabled: true,
      buttonStyle: "glass",
      cardStyle: "glass",
      pageTransition: "scale",
    },
    mascot: {
      type: "cat",
      defaultPose: "hold_flowers",
      animationStyle: "floating",
      size: 160,
      positionX: 50,
      positionY: 80,
      enableFloating: true,
      enableInteractions: true,
      enableBirthdayOutfit: false,
    },
    suggestedCaptions: {
      heading: "Happy Birthday, My Love 💖",
      subheading: "My Heart Belongs to You",
      quote: "Celebrating the day the most beautiful soul entered the world. I love you.",
      buttonText: "Our Story Book",
      footerText: "Yours Forever & Always 🌹",
    }
  },
  best_friend: {
    name: "Best Friend",
    bgMusicUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
    theme: {
      themeName: "Friends Forever",
      primaryColor: "#FFF9C4",
      secondaryColor: "#E0F7FA",
      backgroundColor: "#F9FBE7",
      foregroundColor: "#37474F",
      radius: "16px",
      shadows: "sm",
      cursor: "sparkle",
      loader: "heart",
      fontHeading: "Inter",
      fontBody: "Roboto",
      fontHandwriting: "Patrick Hand",
      backgroundAnimation: "stars",
      stickers: ["🤝", "📸", "🍕", "🎸"],
      icons: "solid",
      balloonsEnabled: false,
      confettiEnabled: true,
      fireworksEnabled: false,
      buttonStyle: "pills",
      cardStyle: "bordered",
      pageTransition: "slide",
    },
    mascot: {
      type: "panda",
      defaultPose: "wave",
      animationStyle: "bounce",
      size: 150,
      positionX: 50,
      positionY: 80,
      enableFloating: false,
      enableInteractions: true,
      enableBirthdayOutfit: false,
    },
    suggestedCaptions: {
      heading: "To My Partner in Crime 🤝",
      subheading: "Thanks for the endless laughters!",
      quote: "Good friends are like stars. You don't always see them, but they are always there.",
      buttonText: "Check Out Memories",
      footerText: "Best Friends Forever 📸",
    }
  },
  anniversary: {
    name: "Anniversary",
    bgMusicUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
    theme: {
      themeName: "Sweet Romance",
      primaryColor: "#FFCDD2",
      secondaryColor: "#FFF9C4",
      backgroundColor: "#FFF5F5",
      foregroundColor: "#4E342E",
      radius: "20px",
      shadows: "lg",
      cursor: "flower",
      loader: "heart",
      fontHeading: "Playfair Display",
      fontBody: "Open Sans",
      fontHandwriting: "Great Vibes",
      backgroundAnimation: "petals",
      stickers: ["🌹", "🕯️", "💍", "🍷"],
      icons: "solid",
      balloonsEnabled: false,
      confettiEnabled: false,
      fireworksEnabled: true,
      buttonStyle: "glass",
      cardStyle: "glass",
      pageTransition: "scale",
    },
    mascot: {
      type: "bunny",
      defaultPose: "hold_flowers",
      animationStyle: "floating",
      size: 165,
      positionX: 50,
      positionY: 80,
      enableFloating: true,
      enableInteractions: true,
      enableBirthdayOutfit: false,
    },
    suggestedCaptions: {
      heading: "Happy Anniversary, My Love 🌹",
      subheading: "Every Single Moment Matters with You",
      quote: "To the person who makes my life full of joy, comfort, and sweet memories.",
      buttonText: "Our Journey",
      footerText: "Forever & Always ❤️",
    }
  },
  proposal: {
    name: "Proposal Surprise",
    bgMusicUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
    theme: {
      themeName: "Will You?",
      primaryColor: "#F8BBD0",
      secondaryColor: "#FFF9C4",
      backgroundColor: "#FFF0F5",
      foregroundColor: "#4A148C",
      radius: "28px",
      shadows: "lg",
      cursor: "heart",
      loader: "heart",
      fontHeading: "Poppins",
      fontBody: "Nunito",
      fontHandwriting: "Pacifico",
      backgroundAnimation: "hearts",
      stickers: ["💍", "🌹", "🕯️", "💖"],
      icons: "solid",
      balloonsEnabled: false,
      confettiEnabled: false,
      fireworksEnabled: true,
      buttonStyle: "glass",
      cardStyle: "glass",
      pageTransition: "flip",
    },
    mascot: {
      type: "cat",
      defaultPose: "hold_gift",
      animationStyle: "floating",
      size: 160,
      positionX: 50,
      positionY: 80,
      enableFloating: true,
      enableInteractions: true,
      enableBirthdayOutfit: false,
    },
    suggestedCaptions: {
      heading: "Will You Marry Me? 💍",
      subheading: "Forever Starts Today, My Love",
      quote: "I want to share all my tomorrows, late-night talks, and adventures with you.",
      buttonText: "My Answer is YES!",
      footerText: "For the rest of our lives 💖",
    }
  },
  wedding: {
    name: "Wedding Theme",
    bgMusicUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3",
    theme: {
      themeName: "Ivory Veil",
      primaryColor: "#E0F2F1",
      secondaryColor: "#FFE082",
      backgroundColor: "#FAF9F6",
      foregroundColor: "#263238",
      radius: "16px",
      shadows: "md",
      cursor: "flower",
      loader: "heart",
      fontHeading: "Playfair Display",
      fontBody: "Inter",
      fontHandwriting: "Great Vibes",
      backgroundAnimation: "petals",
      stickers: ["💍", "🕊️", "🥂", "⛪"],
      icons: "outline",
      balloonsEnabled: false,
      confettiEnabled: true,
      fireworksEnabled: true,
      buttonStyle: "rounded",
      cardStyle: "bordered",
      pageTransition: "fade",
    },
    mascot: {
      type: "bear",
      defaultPose: "hold_gift",
      animationStyle: "floating",
      size: 150,
      positionX: 50,
      positionY: 80,
      enableFloating: true,
      enableInteractions: true,
      enableBirthdayOutfit: false,
    },
    suggestedCaptions: {
      heading: "Our Wedding Day 🕊️",
      subheading: "Together, hand in hand forever",
      quote: "Two lives, two hearts, joined in friendship, united in love.",
      buttonText: "Enter Scrapbook Gallery",
      footerText: "United in Love ⛪",
    }
  },
  graduation: {
    name: "Graduation Gold",
    bgMusicUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3",
    theme: {
      themeName: "Honor Ceremony",
      primaryColor: "#FFE082",
      secondaryColor: "#B2DFDB",
      backgroundColor: "#F4FBFB",
      foregroundColor: "#1A237E",
      radius: "12px",
      shadows: "md",
      cursor: "star",
      loader: "star",
      fontHeading: "Montserrat",
      fontBody: "Nunito",
      fontHandwriting: "Caveat",
      backgroundAnimation: "stars",
      stickers: ["🎓", "📜", "⭐", "🎉"],
      icons: "outline",
      balloonsEnabled: true,
      confettiEnabled: true,
      fireworksEnabled: true,
      buttonStyle: "square",
      cardStyle: "bordered",
      pageTransition: "fade",
    },
    mascot: {
      type: "penguin",
      defaultPose: "celebrate",
      animationStyle: "wiggle",
      size: 145,
      positionX: 50,
      positionY: 80,
      enableFloating: false,
      enableInteractions: true,
      enableBirthdayOutfit: false,
    },
    suggestedCaptions: {
      heading: "Congratulations on Your Graduation! 🎓",
      subheading: "You Did It! A New Journey Begins!",
      quote: "The future belongs to those who believe in the beauty of their dreams.",
      buttonText: "See Achievements",
      footerText: "Class of 2026 📜",
    }
  },
  christmas: {
    name: "Christmas Holiday",
    bgMusicUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3",
    theme: {
      themeName: "Cozy Hearth",
      primaryColor: "#C62828",
      secondaryColor: "#2E7D32",
      backgroundColor: "#F5F5F5",
      foregroundColor: "#1B5E20",
      radius: "20px",
      shadows: "md",
      cursor: "sparkle",
      loader: "gift",
      fontHeading: "Montserrat",
      fontBody: "Nunito",
      fontHandwriting: "Patrick Hand",
      backgroundAnimation: "stars",
      stickers: ["🎄", "❄️", "🎅", "🎁"],
      icons: "solid",
      balloonsEnabled: false,
      confettiEnabled: true,
      fireworksEnabled: false,
      buttonStyle: "rounded",
      cardStyle: "shadow",
      pageTransition: "slide",
    },
    mascot: {
      type: "bear",
      defaultPose: "hold_gift",
      animationStyle: "bounce",
      size: 160,
      positionX: 50,
      positionY: 80,
      enableFloating: false,
      enableInteractions: true,
      enableBirthdayOutfit: true,
    },
    suggestedCaptions: {
      heading: "Merry Christmas! 🎄",
      subheading: "Warmest Wishes & Sweet Surprises",
      quote: "May your holidays be filled with laughter, love, and warm cocoa by the fire.",
      buttonText: "Open Holiday Card",
      footerText: "Wishing you peace & joy ❄️",
    }
  },
  minimal: {
    name: "Sleek Minimalist",
    bgMusicUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3",
    theme: {
      themeName: "Stark White",
      primaryColor: "#212121",
      secondaryColor: "#E0E0E0",
      backgroundColor: "#FFFFFF",
      foregroundColor: "#212121",
      radius: "8px",
      shadows: "sm",
      cursor: "none",
      loader: "star",
      fontHeading: "Inter",
      fontBody: "Inter",
      fontHandwriting: "Patrick Hand",
      backgroundAnimation: "none",
      stickers: ["▪️", "▫️", "✨", "🔘"],
      icons: "outline",
      balloonsEnabled: false,
      confettiEnabled: false,
      fireworksEnabled: false,
      buttonStyle: "square",
      cardStyle: "flat",
      pageTransition: "fade",
    },
    mascot: {
      type: "koala",
      defaultPose: "idle",
      animationStyle: "none",
      size: 140,
      positionX: 50,
      positionY: 80,
      enableFloating: false,
      enableInteractions: false,
      enableBirthdayOutfit: false,
    },
    suggestedCaptions: {
      heading: "Clean & Simple",
      subheading: "A Minimal View of Stories",
      quote: "Simplicity is the ultimate sophistication.",
      buttonText: "Explore",
      footerText: "Minimal Design System",
    }
  },
  pastel: {
    name: "Sweet Pastel",
    bgMusicUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-13.mp3",
    theme: {
      themeName: "Dreamy Mint",
      primaryColor: "#B2DFDB",
      secondaryColor: "#E1BEE7",
      backgroundColor: "#E8F5E9",
      foregroundColor: "#37474F",
      radius: "24px",
      shadows: "md",
      cursor: "flower",
      loader: "heart",
      fontHeading: "Poppins",
      fontBody: "Nunito",
      fontHandwriting: "Caveat",
      backgroundAnimation: "petals",
      stickers: ["🍨", "🍡", "🎨", "🪁"],
      icons: "outline",
      balloonsEnabled: true,
      confettiEnabled: true,
      fireworksEnabled: false,
      buttonStyle: "pills",
      cardStyle: "shadow",
      pageTransition: "scale",
    },
    mascot: {
      type: "hamster",
      defaultPose: "smile",
      animationStyle: "floating",
      size: 140,
      positionX: 50,
      positionY: 80,
      enableFloating: true,
      enableInteractions: true,
      enableBirthdayOutfit: false,
    },
    suggestedCaptions: {
      heading: "Dreamy Pastels 🎨",
      subheading: "Whimsical & Calming Palette",
      quote: "Fill your days with colors that match your sweet and soft imagination.",
      buttonText: "Open Drawer",
      footerText: "Soft Whimsy 🍡",
    }
  },
  galaxy: {
    name: "Deep Space Galaxy",
    bgMusicUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-14.mp3",
    theme: {
      themeName: "Nebula Purple",
      primaryColor: "#E1BEE7",
      secondaryColor: "#0D47A1",
      backgroundColor: "#0A0015",
      foregroundColor: "#E0E0E0",
      radius: "16px",
      shadows: "lg",
      cursor: "star",
      loader: "star",
      fontHeading: "Montserrat",
      fontBody: "Inter",
      fontHandwriting: "Caveat",
      backgroundAnimation: "stars",
      stickers: ["🛸", "🪐", "⭐", "🌌"],
      icons: "solid",
      balloonsEnabled: false,
      confettiEnabled: false,
      fireworksEnabled: true,
      buttonStyle: "rounded",
      cardStyle: "glass",
      pageTransition: "flip",
    },
    mascot: {
      type: "fox",
      defaultPose: "celebrate",
      animationStyle: "floating",
      size: 155,
      positionX: 50,
      positionY: 80,
      enableFloating: true,
      enableInteractions: true,
      enableBirthdayOutfit: false,
    },
    suggestedCaptions: {
      heading: "Beyond the Stars 🪐",
      subheading: "A Galaxy of Memories Just for You",
      quote: "You are the universe expressing itself in a beautiful collection of code and stardust.",
      buttonText: "Blast Off",
      footerText: "To infinity & beyond 🚀",
    }
  },
  anime: {
    name: "Otaku Anime",
    bgMusicUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-15.mp3",
    theme: {
      themeName: "Shibuya Sky",
      primaryColor: "#FF4081",
      secondaryColor: "#00E5FF",
      backgroundColor: "#FFF0F5",
      foregroundColor: "#2A363B",
      radius: "20px",
      shadows: "md",
      cursor: "sparkle",
      loader: "cake",
      fontHeading: "Poppins",
      fontBody: "Nunito",
      fontHandwriting: "Pacifico",
      backgroundAnimation: "confetti",
      stickers: ["🌸", "🍜", "🦊", "🍡"],
      icons: "solid",
      balloonsEnabled: true,
      confettiEnabled: true,
      fireworksEnabled: true,
      buttonStyle: "rounded",
      cardStyle: "shadow",
      pageTransition: "scale",
    },
    mascot: {
      type: "frog",
      defaultPose: "jump",
      animationStyle: "bounce",
      size: 150,
      positionX: 50,
      positionY: 80,
      enableFloating: false,
      enableInteractions: true,
      enableBirthdayOutfit: true,
    },
    suggestedCaptions: {
      heading: "Senpai, Surprise! 🌸",
      subheading: "An Anime Aesthetic Card",
      quote: "No matter how tough today gets, remember that your main character arc is just beginning!",
      buttonText: "Start Arc",
      footerText: "Arigato Gozaimasu! 🦊",
    }
  },
  vintage: {
    name: "Vintage Sepia",
    bgMusicUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    theme: {
      themeName: "Retro Typewriter",
      primaryColor: "#8D6E63",
      secondaryColor: "#D7CCC8",
      backgroundColor: "#EFEBE9",
      foregroundColor: "#3E2723",
      radius: "8px",
      shadows: "sm",
      cursor: "none",
      loader: "star",
      fontHeading: "Playfair Display",
      fontBody: "Roboto",
      fontHandwriting: "Great Vibes",
      backgroundAnimation: "none",
      stickers: ["🕰️", "📜", "🕯️", "🤎"],
      icons: "outline",
      balloonsEnabled: false,
      confettiEnabled: false,
      fireworksEnabled: false,
      buttonStyle: "square",
      cardStyle: "bordered",
      pageTransition: "fade",
    },
    mascot: {
      type: "bear",
      defaultPose: "idle",
      animationStyle: "none",
      size: 150,
      positionX: 50,
      positionY: 80,
      enableFloating: false,
      enableInteractions: true,
      enableBirthdayOutfit: false,
    },
    suggestedCaptions: {
      heading: "A Chapter from the Past 🕰️",
      subheading: "Classic Scrapbook Layout",
      quote: "Memories are the architecture of our heart's favorite places.",
      buttonText: "Open Chapter",
      footerText: "Vintage Archive 📜",
    }
  },
  nature: {
    name: "Cozy Forest Nature",
    bgMusicUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
    theme: {
      themeName: "Forest Sage",
      primaryColor: "#A5D6A7",
      secondaryColor: "#FFE082",
      backgroundColor: "#E8F5E9",
      foregroundColor: "#1B5E20",
      radius: "24px",
      shadows: "md",
      cursor: "flower",
      loader: "star",
      fontHeading: "Montserrat",
      fontBody: "Nunito",
      fontHandwriting: "Caveat",
      backgroundAnimation: "petals",
      stickers: ["🍃", "🌻", "🏕️", "🦊"],
      icons: "outline",
      balloonsEnabled: false,
      confettiEnabled: false,
      fireworksEnabled: false,
      buttonStyle: "rounded",
      cardStyle: "shadow",
      pageTransition: "fade",
    },
    mascot: {
      type: "fox",
      defaultPose: "smile",
      animationStyle: "floating",
      size: 155,
      positionX: 50,
      positionY: 80,
      enableFloating: true,
      enableInteractions: true,
      enableBirthdayOutfit: false,
    },
    suggestedCaptions: {
      heading: "Into the Cozy Woods 🍃",
      subheading: "Breathe in, Breathe out, Celebrate!",
      quote: "Look deep into nature, and then you will understand everything better.",
      buttonText: "Walk In",
      footerText: "Nature Sanctuary 🌻",
    }
  },
  luxury: {
    name: "Luxury VIP Platinum",
    bgMusicUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    theme: {
      themeName: "Platinum Satin",
      primaryColor: "#B0BEC5",
      secondaryColor: "#37474F",
      backgroundColor: "#ECEFF1",
      foregroundColor: "#263238",
      radius: "16px",
      shadows: "lg",
      cursor: "sparkle",
      loader: "star",
      fontHeading: "Playfair Display",
      fontBody: "Inter",
      fontHandwriting: "Great Vibes",
      backgroundAnimation: "stars",
      stickers: ["💎", "🤵", "🍷", "🕯️"],
      icons: "outline",
      balloonsEnabled: false,
      confettiEnabled: false,
      fireworksEnabled: true,
      buttonStyle: "square",
      cardStyle: "glass",
      pageTransition: "scale",
    },
    mascot: {
      type: "giraffe",
      defaultPose: "idle",
      animationStyle: "floating",
      size: 165,
      positionX: 50,
      positionY: 80,
      enableFloating: true,
      enableInteractions: true,
      enableBirthdayOutfit: false,
    },
    suggestedCaptions: {
      heading: "A Platinum Surprise 💎",
      subheading: "Reserved Especially For You",
      quote: "Quality means doing it right when no one is looking. Live gracefully.",
      buttonText: "Enter Private Lounge",
      footerText: "Platinum Lounge Reserve 🍷",
    }
  }
};
